---
language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements-dev.txt
  - pip install .
# command to run tests
script: python setup.py test
before_install:
  - pip install codecov
after_success:
  - codecov
