---
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install .
# command to run tests
script: python setup.py test
before_install:
  - pip install codecov
after_success:
  - codecov